apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-oxp2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-oxp2
    app.kubernetes.io/part-of: ci1t-43256-0093-app
  name: devfile-sample-oxp2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-oxp2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-oxp2
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0093-tenant/ci1t-43256-0093-app/devfile-sample-oxp2@sha256:35e4f6c61394e3fea948a776b2ad399e39c1304a25763c9e15da6f91bf0af38c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
