apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-oxp2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-oxp2
    app.kubernetes.io/part-of: ci1t-43256-0093-app
  name: devfile-sample-oxp2s7kt
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-oxp2
    weight: null
status: {}
